name: Prepare All

on:
  workflow_call:

jobs:
  prepare-all:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21" # keep the same as your Android Studio version
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
