name: Test Android and iOS Debug Builds

on: [ push ] # run on all pushes on any branch

jobs:
  build:
    runs-on: [ self-hosted, macOS ] # use [ self-hosted, macOS ] to host on our own mac mini, which is twice as fast and cheaper than hosting on a github runner. See README for more info.
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: "21" # keep the same as your Android Studio version
          cache: 'gradle' # cache gradle dependencies for faster builds

      - name: Build Debug APK
        run: ./gradlew :composeApp:assemble --stacktrace -x :composeApp:linkDebugFrameworkIosSimulatorArm64 -x :composeApp:linkReleaseFrameworkIosSimulatorArm64

      - name: Run all tests on Android and iOS
        run: ./gradlew check --stacktrace -x :composeApp:iosSimulatorArm64Test

      - name: Upload Dev Debug APK to Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ github.event.repository.name }}-${{ github.run_number }}-debug-apk
          path: |
            ${{ github.workspace }}/composeApp/build/outputs/apk/debug/composeApp-debug.apk
