name: Test Android and iOS Debug Builds

on: [ push ] # run on all pushes on any branch

jobs:
  prepare-all:
    uses: ./.github/workflows/_prepare-all.yml
  build:
    runs-on: macos-latest # use [ self-hosted, macOS ] to host on our own mac mini, which is twice as fast and cheaper than hosting on a github runner. See README for more info.
    steps:
      - uses: actions/checkout@v4

      - name: Cache gradle, wrapper and buildSrc
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Debug APK
        run: ./gradlew :composeApp:assemble --stacktrace

      - name: Run all tests on Android and iOS
        run: ./gradlew check --stacktrace

      - name: Upload Dev Debug APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.run_number }}-debug-apk
          path: |
            ${{ github.workspace }}/composeApp/build/outputs/apk/debug/composeApp-debug.apk
